# Generated by Django 2.2.2 on 2021-01-21 23:45

from django.db import migrations, models
import project.apps.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=project.apps.projects.models.path_file_and_rename),
        ),
        migrations.AddField(
            model_name='projects',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Android'), (2, 'Web'), (3, 'Backend'), (4, 'IOS'), (5, 'Flutter')], null=True),
        ),
    ]
