# Generated by Django 2.2.2 on 2021-01-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_auto_20190527_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
